query GetAllRecipes {
  allRecipes {
    excerpt
    id
    slug
    updatedAt
    featuredImage {
      url
    }
    description {
      value
    }
    ingredients {
      title
      unit
      quantity
      id
    }
    title
  }
}

query GetSingleRecipe($slug: String!) {
  recipe(filter: { slug: { eq: $slug } }) {
    title
    slug
    updatedAt
    id
    featuredImage {
      url
    }
    description {
      value
    }
    ingredients {
      id
      quantity
      unit
      title
    }
  }
}
